import slugify from 'slugify';
import Novel from '../models/Novel.js';
import Chapter from '../models/Chapter.js';
import User from '../models/User.js';
import Bookmark from '../models/Bookmark.js';
import Comment from '../models/Comment.js';
import { uploadBuffer } from '../utils/cloudinaryUpload.js';

async function uniqueSlug(title,id){let base=slugify(title,{lower:true,strict:true})||`novel-${Date.now()}`;let slug=base,n=1;while(await Novel.findOne({slug,_id:{$ne:id}}))slug=`${base}-${n++}`;return slug}
export async function dashboard(req,res,next){try{const [totalNovels,publishedNovels,totalChapters,publishedChapters,totalUsers,bannedUsers,pendingComments,approvedComments,totalBookmarks,viewAgg,likeAgg]=await Promise.all([Novel.countDocuments(),Novel.countDocuments({publishStatus:'PUBLISHED'}),Chapter.countDocuments(),Chapter.countDocuments({publishStatus:'PUBLISHED'}),User.countDocuments({role:'USER'}),User.countDocuments({isBanned:true}),Comment.countDocuments({status:'PENDING'}),Comment.countDocuments({status:'APPROVED'}),Bookmark.countDocuments(),Chapter.aggregate([{$group:{_id:null,n:{$sum:'$views'}}}]),Chapter.aggregate([{$project:{n:{$size:'$likedBy'}}},{$group:{_id:null,n:{$sum:'$n'}}}])]);res.json({success:true,stats:{totalNovels,publishedNovels,draftNovels:totalNovels-publishedNovels,totalChapters,publishedChapters,draftChapters:totalChapters-publishedChapters,totalUsers,bannedUsers,pendingComments,approvedComments,totalBookmarks,totalViews:viewAgg[0]?.n||0,totalLikes:likeAgg[0]?.n||0}})}catch(e){next(e)}}
export async function adminNovels(req,res,next){try{res.json({success:true,novels:await Novel.find().sort({updatedAt:-1})})}catch(e){next(e)}}
export async function createNovel(req,res,next){try{const body=req.body;let image={};if(req.file){const r=await uploadBuffer(req.file.buffer);image={coverImageUrl:r.secure_url,coverImagePublicId:r.public_id}}const novel=await Novel.create({...body,slug:await uniqueSlug(body.title),tags:body.tags?String(body.tags).split(',').map(x=>x.trim()).filter(Boolean):[],...image});res.status(201).json({success:true,novel})}catch(e){next(e)}}
export async function updateNovel(req,res,next){try{const body=req.body;let update={...body};if(body.title)update.slug=await uniqueSlug(body.title,req.params.novelId);if(body.tags)update.tags=String(body.tags).split(',').map(x=>x.trim()).filter(Boolean);if(req.file){const r=await uploadBuffer(req.file.buffer);update.coverImageUrl=r.secure_url;update.coverImagePublicId=r.public_id}const novel=await Novel.findByIdAndUpdate(req.params.novelId,update,{new:true,runValidators:true});res.json({success:true,novel})}catch(e){next(e)}}
export async function toggleNovel(req,res,next){try{const novel=await Novel.findById(req.params.novelId);if(!novel)return res.status(404).json({success:false,message:'Novel not found'});novel.publishStatus=novel.publishStatus==='PUBLISHED'?'DRAFT':'PUBLISHED';await novel.save();res.json({success:true,novel})}catch(e){next(e)}}
export async function deleteNovel(req,res,next){try{const id=req.params.novelId;const chapters=await Chapter.find({novelId:id}).select('_id');const ids=chapters.map(c=>c._id);await Promise.all([Chapter.deleteMany({novelId:id}),Bookmark.deleteMany({novelId:id}),Comment.deleteMany({novelId:id}),Novel.findByIdAndDelete(id)]);res.json({success:true,message:'Novel deleted'})}catch(e){next(e)}}
export async function chapters(req,res,next){try{res.json({success:true,chapters:await Chapter.find({novelId:req.params.novelId}).sort({chapterNumber:1})})}catch(e){next(e)}}
export async function createChapter(req,res,next){try{const chapter=await Chapter.create({...req.body,novelId:req.params.novelId,publishedAt:req.body.publishStatus==='PUBLISHED'?new Date():undefined});res.status(201).json({success:true,chapter})}catch(e){next(e)}}
export async function updateChapter(req,res,next){try{const update={...req.body};if(req.body.publishStatus==='PUBLISHED')update.publishedAt=new Date();const chapter=await Chapter.findByIdAndUpdate(req.params.chapterId,update,{new:true,runValidators:true});res.json({success:true,chapter})}catch(e){next(e)}}
export async function toggleChapter(req,res,next){try{const c=await Chapter.findById(req.params.chapterId);if(!c)return res.status(404).json({success:false,message:'Chapter not found'});c.publishStatus=c.publishStatus==='PUBLISHED'?'DRAFT':'PUBLISHED';c.publishedAt=c.publishStatus==='PUBLISHED'?new Date():undefined;await c.save();res.json({success:true,chapter:c})}catch(e){next(e)}}
export async function deleteChapter(req,res,next){try{const id=req.params.chapterId;await Promise.all([Chapter.findByIdAndDelete(id),Bookmark.deleteMany({chapterId:id}),Comment.deleteMany({chapterId:id})]);res.json({success:true,message:'Chapter deleted'})}catch(e){next(e)}}
export async function users(req,res,next){try{res.json({success:true,users:await User.find({role:'USER'}).select('-password').sort({createdAt:-1})})}catch(e){next(e)}}
export async function ban(req,res,next){try{if(!req.body.reason?.trim())return res.status(400).json({success:false,message:'Ban reason is required'});const user=await User.findByIdAndUpdate(req.params.userId,{isBanned:true,banReason:req.body.reason,bannedAt:new Date()},{new:true}).select('-password');res.json({success:true,user})}catch(e){next(e)}}
export async function unban(req,res,next){try{const user=await User.findByIdAndUpdate(req.params.userId,{isBanned:false,banReason:'',$unset:{bannedAt:1}},{new:true}).select('-password');res.json({success:true,user})}catch(e){next(e)}}
export async function deleteUser(req,res,next){try{const id=req.params.userId;await Promise.all([Bookmark.deleteMany({userId:id}),Comment.deleteMany({userId:id}),Chapter.updateMany({},{$pull:{likedBy:id}}),User.findByIdAndDelete(id)]);res.json({success:true,message:'User deleted'})}catch(e){next(e)}}
export async function comments(req,res,next){try{res.json({success:true,comments:await Comment.find().populate('userId','name email').populate('novelId','title').populate('chapterId','title chapterNumber').sort({createdAt:-1})})}catch(e){next(e)}}
export async function approve(req,res,next){try{const c=await Comment.findByIdAndUpdate(req.params.commentId,{status:'APPROVED'},{new:true});res.json({success:true,comment:c})}catch(e){next(e)}}
export async function deleteComment(req,res,next){try{await Comment.findByIdAndDelete(req.params.commentId);res.json({success:true,message:'Comment deleted'})}catch(e){next(e)}}
